name: Generate Manifests

on:
  release:
    types: [published]
  workflow_dispatch: 
    inputs:
      version:
        type: string
        required: true

env:
  MANIFESTS_FILENAME: manifests.yaml
  KUSTOMIZE_VERSION: 5.8.1

jobs:
  generate-manifests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: |
          if [[ ! -z '${{ inputs.version }}' ]]
          then
            echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Setup Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash -s -- ${{ env.KUSTOMIZE_VERSION }}
          sudo mv kustomize /usr/local/bin/

      - name: Print version
        run: |
          echo "Version=${{ steps.get_version.outputs.version }}"

      - name: Update version in kustomization.yaml & default CRO
        run: |
          yq -i '.images[0].newTag="${{ steps.get_version.outputs.version }}"' config/default/kustomization.yaml

      - name: Generate manifests
        run: |
          kustomize build ./config/default > ${{ env.MANIFESTS_FILENAME }}

      - name: Upload manifests to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ env.MANIFESTS_FILENAME }}
          asset_name: ${{ env.MANIFESTS_FILENAME }}
          asset_content_type: application/x-yaml